@hostname = localhost
@port = 32772
@host = http://{{hostname}}:{{port}}
@contentType = application/json

###
POST {{host}}/graphql/
Content-Type: {{contentType}}
X-REQUEST-TYPE: GraphQL

query {
    allBoards {
        id
        title
        content
    }
}


###
POST {{host}}/graphql/
Content-Type: {{contentType}}
X-REQUEST-TYPE: GraphQL

query {
    board(id: 2) {
        id
        title
        content
    }
}