# Generated by Django 3.0.8 on 2020-10-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20201013_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, upload_to='boards/%Y/%m/%d'),
        ),
    ]
